name: build and publish docker custom images to github package registry
on: [push]

jobs:
  build_and_publish:
    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ubuntu:
              - 'ubuntu/**'
            amzn-linux:
              - 'amzn-linux/**'
            alpine:
              - 'alpine/**'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: login to github packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push ubuntu image
        if: steps.filter.outputs.ubuntu == 'true'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./ubuntu
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/extrinsec/docker/ubuntu:latest

      - name: build and push amzn-linux image
        if: steps.filter.outputs.amzn-linux == 'true'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./amzn-linux
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/extrinsec/docker/amzn-linux:latest

      - name: build and push alpine image
        if: steps.filter.outputs.alpine == 'true'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./alpine
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/extrinsec/docker/alpine:latest